# ~~~ How to use Appveyor ~~~
# Preconditions: Artifactory with external access.
#
# = Trigger tests on commits =
#   1. Create a new project in Appveyor and choose jenkins-artifactory-plugin.
#   2. In project settings, copy the 'Webhook URL' and create a new 'Push events' Webhook in Github.
#
# = Configure Artifactory =
#   Create a remote Nuget repository in Artifactory:
#     A. Repository Key: choco
#     B. Url: https://chocolatey.org
#     * The test uses Chocolatey package manager to download Maven and Gradle Nuget packages through Artifactory's cache.
#
# = Override credentials in Appveyor in case of a fork =
#   1. In the project at Appveyor - Go to settings -> Environment.
#   2. Override 'JENKINS_PLATFORM_URL' and 'JENKINS_ARTIFACTORY_USERNAME'.
#   3. Override 'JENKINS_ARTIFACTORY_PASSWORD' with variable encryption.

stack: jdk 8, node 8, python 3.9
skip_tags: true
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  USE_UNSUPPORTED_CONAN_WITH_PYTHON_2: true

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      # .NET CLI version
      CLI_VERSION: Latest
      JENKINS_PIP_ENV_INIT: C:\\projects\\jenkins-artifactory-plugin\\pip-venv\\Scripts\\activate.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JENKINS_PIP_ENV_INIT: ""

services:
  - docker
before_test:
  - cmd: "choco install maven --version 3.3.9.2 -i -s %JENKINS_PLATFORM_URL%/artifactory/api/nuget/choco -u %JENKINS_ARTIFACTORY_USERNAME% -p %JENKINS_ARTIFACTORY_PASSWORD%"
  - cmd: "choco install gradle --version 6.5.1 -i -s %JENKINS_PLATFORM_URL%/artifactory/api/nuget/choco -u %JENKINS_ARTIFACTORY_USERNAME% -p %JENKINS_ARTIFACTORY_PASSWORD%"
  - cmd: refreshenv
  - cmd: pip install conan -q
  - cmd: "C:\\Python37-x64\\python -m venv pip-venv"
  - sh: sudo pip install conan -q
  - sh: curl -s "https://get.sdkman.io" | bash
  - sh: source "/home/appveyor/.sdkman/bin/sdkman-init.sh"
  - sh: export MAVEN_HOME=/home/appveyor/.sdkman/candidates/maven/current && sdk use maven 3.3.9 || sdk install maven 3.3.9
  - sh: export GRADLE_HOME=/home/appveyor/.sdkman/candidates/gradle/current && sdk use gradle 6.5.1 || sdk install gradle 6.5.1
  - sh: export PYTHON=$HOME/venv3.7.9
  - sh: python -m venv pip-venv
  - sh: source /home/appveyor/projects/jenkins-artifactory-plugin/pip-venv/bin/activate
  - sh: touch tests.log
  - sh: tail -f tests.log &

test_script:
  - mvn -V -B -U clean verify -DskipITs=false -Djna.nosys=true

cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
  - /home/appveyor/.m2/ -> pom.xml
  - /home/appveyor/.sdkman/ -> appveyor.yml

build: off
